theme: Campanha de arrecadação de ofertas, chamada "Adote um Adolescente do Sertão" , para custear a viagem e a inscrição de jovens do sertão pernambucano no acampamento da igreja (ACAMP PBT 2025)
title: Adote um Adolescente do Sertão | ACAMP PBT 2025
description: Ajude-nos a levar mais de 15 jovens para o Acamp PBT 2025. Uma experiência de fé, comunhão e transformação de vidas.
